version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 22.x  # Specify the Node.js version you are using
    commands:
      # Install dependencies (if any)
      - echo "Installing npm dependencies..."
      - npm install
 
  pre_build:
    commands:
      # Run tests (optional, if you have any)
      - echo "Running tests..."
      # npm test  # If you have unit tests
 
  build:
    commands:
      # Create a zip file including everything in the root directory
      - echo "Zipping the whole application..."
      - zip -r bookstore.zip .  # Zips the entire project folder (including node_modules, src, etc.)
 
      # Upload the zip file to S3
      - echo "Uploading book-store.zip to S3..."
      - aws s3 cp book-store.zip s3://bookstores-lambda-code/bookstore.zip  # Replace with your S3 bucket name
 
  post_build:
    commands:
      # Deploy Lambda function from the S3 bucket
      - echo "Updating Lambda functions..."
 
      # Lambda Function 1
      - aws lambda update-function-code --function-name getBooks --s3-bucket bookstores-lambda-code --s3-key bookstore.zip
      - echo "Lambda function 1 deployed successfully!"
 
artifacts:
  files:
    - '**/*'
  discard-paths: yes